# Generated by Django 3.1.7 on 2021-04-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210404_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(to='bookstore.Book'),
        ),
    ]
